### ISSUE TITLE
Liczenie punktów

### ISSUE THREAD

**Issue by tgandor** [Jgandor/Informatyka#2]
Brakuje liczenia punktów.

Powinny być liczone i wypisywać się przed każdym pytaniem.
Proponowana punktacja:
* dobra odpowiedź +2
* dobra po czasie +1
* zła odpowiedź -1
* zła odpowiedź po czasie -2

**Comment by Jgandor** [comment]
Poprawiłem, dzięki.

**Comment by tgandor** [comment]
Jest OK.
