### ISSUE TITLE
Błąd w obliczaniu średniej

### ISSUE THREAD

**Issue by tgandor** [Jgandor/Informatyka#4]
Poniżej przykład działania programu:

```
~/git/Informatyka$ python Srednia.py
Podaj pierwszą liczbę: 8
Podaj pierwszą liczbę: 6
Średnia artmetyczna tych liczb wynosi:  24.0
```

Prawidłowa odpowiedź powinna być: 7.0

**Comment by Jgandor** [comment]
Działa, jak mówiłeś. (Dodawanie #4 dodało jako komentarz)

**Comment by Jgandor** [comment]
Poprawiłem program, zamiast dodawać, mnożył i to był cały problem.

**Comment by tgandor** [comment]
OK, może być.
